Vagrant.configure("2") do |sonarqube|
  sonarqube.vm.box = "centos/7"
  sonarqube.vm.hostname = "sonarqube"
  
  sonarqube.vm.network "forwarded_port", guest: 9000, host: 9000, hostip: "127.0.0.1"
  
  sonarqube.vm.network "private_network", ip: "192.168.56.4"
  
  sonarqube.vm.provision "shell", path: "sonarqube.sh"
  
  sonarqube.vm.provider "virtualbox" do |v|
    v.memory = 1024
    end
end
