Vagrant.configure("2") do |jenkins|
    jenkins.vm.box = "centos/7"
    jenkins.vm.hostname = "jenkins"

    jenkins.vm.network "forwarded_port", guest: 80, host: 8080, hostip: "127.0.0.1"
    jenkins.vm.network "forwarded_port", guest: 8091, host: 8091, hostip: "127.0.0.1"

    jenkins.vm.network "private_network", ip: "192.168.56.3"

    jenkins.vm.provision "shell", path: "jenkins.sh"

    jenkins.vm.provider "virtualbox" do |v|
    v.memory = 2048
    end
end